### ISSUE TITLE
Memory Leak? 

### ISSUE THREAD

**Issue by jermowatson** [drkameleon/iswift#16]
When pasting or opening a .m file that is more than a 1000 lines of code iSwift slows down. 

Steps to reproduce:
1.) Open up iSwift
2.) Copy and paste a large .m file with various functions OR open up .m file

Expected results:
The application should parse through the .m file and lines of code and produce the Swift conversion. 

Actual results:
The application is still responsive however its so slow that the conversion often never eventuates. Occasionally cause iSwift to crash. 

System:
MacBook Pro 16GB Memory, 2.6 GHZ, 

Open Applications:
Safari, XCode, iSwift, Mail.

**Comment by drkameleon** [comment]
Jeremy, I know what you're talking about and I can already reproduce it.

Now, here's what: iSwift's core idea is to have everything translated as-you-type. Meaning: you add a single character, the code changes and the whole thing is being parsed from scratch - reporting errors or showing the updated output.

This is fine, but obviously with code files of some limited size (yes, the parser *is* fast, but possibly not as fast to parse thousands of code lines instantly, so that you don't even notice). And that's what happened here.

So, what I'm planning to do is: add a Preferences option so that you can enable/disable live syntax checking and conversion (if you wish), in which case the conversion will be "on demand". In a few words, with a "Convert" button.

I'm still thinking of ways to go around this, so I'm open to suggestions!

**Comment by jermowatson** [comment]
Oh okay,

Sounds good. I would give the option as that would make life a little easier for those who only want to do function by function vs full file. I would like to do both. One big button to say here is my project “FIX it”. Of course the reality is that I would have to review each area. But now that I understand the limitation of iSwift that makes sense. 

I do like the ability of switching off the parser kind of build later when I’m ready. 

Also thought of another idea today where you load up one page and then have a back arrow (when appropriate) to another page that you loaded up earlier. I very similar how XCode does it. Makes it a little easier to remember where I was up to. Of course this is a feature request so bottom of the pile. :-P. 

Regards,
Jeremy

**Comment by drkameleon** [comment]
> Also thought of another idea today where you load up one page and then have a back arrow (when appropriate) to another page that you loaded up earlier. I very similar how XCode does it. Makes it a little easier to remember where I was up to. Of course this is a feature request so bottom of the pile. :-P.

Can you please elaborate a bit on that? I'm not sure I get you mean... :)

**Comment by drkameleon** [comment]
Also, regarding the initial issue:

Along with a Preferences panel, I've added an option to enable/disable Live Conversion. Now, this - at least for me - has dramatically improved things. It's not perfect - yet (I'm working on it) - with some 1-2k+ files it *may* freeze a little bit when clicking the ">" button, in order to manually convert your code. But I believe it's getting better. I'm looking forward to your feedback - once the new 1.3 goes live, that is. ;-)

**Comment by jermowatson** [comment]
Yeah,

It was late in the evening and I wasn’t making to much sense I feel. Let me start over. 

1.) Load up a .M file in the left hand view
2.) Automagically converts to swift
3.) Load up a new page (because we have so many .m files in objective c)
4.) Automagically converts to swift 
5.) Now go back to the first .M file because you wanted to see something specific ( I would imagine this would still be in the memory perhaps )

Below screen shot in Xcode with the arrows. 




I realise this is pretty basic but if your doing a number of conversions and for some reason it doesn’t work accordingly on one file but it did on another go back to see the other file may be handy going forward. Its just an idea and doesn’t have to go in. 

Jeremy

**Comment by drkameleon** [comment]
Marking the main issue as closed and moving the discussion (regarding the last suggestion) here: https://github.com/drkameleon/iswift/issues/47
