### ISSUE TITLE
Conversion stalls at first unknown syntax

### ISSUE THREAD

**Issue by ExtelligentCocoa** [drkameleon/iswift#170]
Short form: iSwift is completely useless
Longer form: I purchased iSwift recently as part of a StackSocial 4-in-1 bundle deal and was very excited about this application. I started it under 10.10.5, converted my first ObjectiveC file to Swift, loaded a second and found that iSwift absolutely and utterly resolutely refused to flush the buffer and translate the second file. The effort of the first part was reasonable - not particularly great (and not particularly correct in places), but gave me a good starting point: but that was it. Further conversions were just not happening.
So I cannot say I was overly surprised when I booted up into 10.11 (this is a dual boot system) and found the same refusal to convert even a single line of code. All it said in the corner was 'unexpected @'. Which, fine. I wasn't expecting @import, either, but that's not a fatal error. Nobody can keep every variant of Objective C straight

I then tried out the website conversion,  which is a little more verbose: /*
Unexpected :  @

Expected   :
'NULLABLE', 'NONNULL', const, volatile, 'NONNULL_', 'NULLABLE_', '&', '*', '+', '-', '~', '!', typedef, extern, static, auto, register, 'BLOCK___', 'WEAK___', void, char, short, int, long, float, double, Class, id, SEL, BOOL, signed, unsigned, #type, 'USER_TYPE_NAME', struct, union, #identifier, '{', ';', enum, 'NS_ENUM', '(', 'NS_OPTIONS', '[', '^', #constant, #string, 'CHAR_LITERAL', self, super, '@', NIL, YES, NO, @selector, 'ENCODE_', @protocol, '++', '--', sizeof, case, default, if, switch, while, do, for, goto, continue, break, return, #ifdef, #ifndef, #ident, #include, #undef, #import, #define, #pragma, #if, 'ELIF__', #else, #endif, @try, @autoreleasepool, 'THROW_', 'COMMENT_MULTI', 'COMMENT_SINGLE'
*/
You appear to have written a coding tool that, at the first line that it doesn't recognise (and if it cannot recognise a line beginning with @property, there's really not much hope for it) completely throws all of its toys out of the pram? Instead of just commenting out the offending line, maybe with 'cannot convert' and then CONTINUING WITH THE CONVERSION?

Commenting out the offending line does trigger the conversion of the rest of the file, but that doesn't explain the online failure of failure to convert
@property (weak) IBOutlet NSTextField *titleTextField;  
which the online tool also choked on.

**Comment by drkameleon** [comment]
Well, let me explain what is going on.

iSwift is built as a pure compiler/parser, meaning it was originally aimed to convert complete Xcode-valid code files (with `@implementation` and all that), and not code snippets. In a few words: what doesn't compile in Xcode, wouldn't "compile" in iSwift as well.

Now, as of the last few updates (see: "Can I convert code blocks?" under FAQ: https://github.com/drkameleon/iswift/wiki/FAQ) I've been trying to extend conversion even to simple statements. And all that a lot of progress has been made, code snippet conversion is most definitely not at its best. Meaning: `@property`s are obviously recognised but not as a standalone statement. (As part of a Class' interface, it'd sure work fine).

So, to sum up...

#### What does iSwift recognize?

Valid Objective-C code (Xcode-wise).

**Example:**

``` objective-c
@interface someClass

@property (weak) IBOutlet NSTextField *titleTextField;

@end
@implementation someClass

@end
```

#### Does it convert simple statements or random Objective-C snippets?

Yes. And no.

Something like `NSString* someString = @"hello world";` would work (and lots more too - like loops, conditionals, etc). But a single `@property` statement will not. For now that is.

Now, regarding... fault tolerance, I do get your point. And I get it that the whole error reporting should have been more flexible. I assure you I'm doing my best to make it as good as it gets. 

And that's why your feedback is valuable. Keep it coming - it's more than welcome! :)

**Comment by nemesit** [comment]
it is unable to convert even the most simple code ;-p you should learn objective-c first sry.
