### ISSUE TITLE
Is iSwift still being developed?

### ISSUE THREAD

**Issue by daviddelmonte** [drkameleon/iswift#193]
The last commit was 8 months ago. If not, I would appreciate a Paypal refund.

**Comment by ThaNerd** [comment]
Same for me. I've tried to use it to convert dozens of Apple Dev website sample code, and so far NONE worked in your app. there's always a "unexpected" error in the bottom right, and I have to find a way to "debug" code that actually compiles in Xcode, while I bought this app because I have no experience of Objective-C.

The rare occasions where I threw in Objective-C code that the app somehow converted, pasting it in Xcode lead to many errors. And yes, there have been no update in a while, and I'm pretty sure nothing is compatible with current Swift 3 nor even Swift 2.2.

This is really a scam!

**Comment by drkameleon** [comment]
Guys,

Apologies for the delay - but I guess it's one of those times where "real life" interferes with any of my/our/etc plans and... things get delayed. This is exactly the case with iSwift. So, I apologize for that.

However, iSwift is by no means "dead" - and will soon make its comeback. Slow but... steady - I hope. :)

In the meantime, seeing any possible issue posted by you guys would definitely do no harm, as it's what fuels future updates and the app getting better. It's the community that has pushed iSwift that far, so I'm more than grateful.

Finally, if you're still not satisfied - which I will understand - feel free to let me know via e-mail and I will issue a refund asap. My goal is not to scam anyone, but create something useful for everyone (myself included)... ;-)

Cheers!
