### ISSUE TITLE
@Synthesize Value Errors and prevents conversion. 

### ISSUE THREAD

**Issue by jermowatson** [drkameleon/iswift#36]
There seems to be an issue when trying to convert @Synthesize. Now I know the Swift does things slightly different as in some things are not needed. However, I am unsure if this is an issue or by design. 

Try with the following code:
@synthesize copyrightLabel;

Expected Results:
Perhaps blank? Not sure. 
var copyrightLabel?

Actual Results:
Error's out at @Synthesize Line.

**Comment by drkameleon** [comment]
Well, good catch.

First, let me tell you that `@synthesize` is (one of the few things left I believe) not implemented.

Now, regarding how it is to be translated (which I'll do very soon, since you reminded me), that's interesting:

since a `@synthesize` statetement usually corresponded to a `@property` and properties *are* being handled (where you *can* tell the variable's type), I believe we should stick to the `@property` translation - provided the header is also there. (Or that the header/interface part is copy-pasted on top of the implementation source).

I'm open to suggestions. Not throwing an error for `@synthesize` statements *can* and *will* be done. I'm just not sure if it's any use handling it somehow....

**Comment by jermowatson** [comment]
Yeah, I wasn’t sure either. 

It really is in theory usually in the .h file or some other variable as you suggested. I can’t see a use case to use it. So yeah I agree perhaps omit it out until there is a Use Case where we need it..I just wasn’t sure how. 

Omit and we can go from there.

**Comment by drkameleon** [comment]
Basically my doubt is:

If you just cp-paste the `@implementation` part and want the `@synthesize` statements to be converted to the corresponding vars, that's fine. But, given that `@synthesize` doesn't tell us anything about the type, how practical would that be? OK, obviously, something (without have the header there I mean) is better than nothing. I'm just not sure whether this would solve more issues than what it can create.

**Comment by jermowatson** [comment]
Agreed.

**Comment by drkameleon** [comment]
Fixed as of the upcoming 1.5.
