### ISSUE TITLE
Global Objects Referencing preventing further conversion. 

### ISSUE THREAD

**Issue by jermowatson** [drkameleon/iswift#37]
When referencing a global object as indicated with the code below from another .m file (NSObject or other) it fails on the = I believe. 

Try with the following code:
GlobalObjects *setObjects = [GlobalObjects sharedGlobalObjects];

Expected Results:
Perhaps: var setObjects: GlobalObjects = GlobalObjects.sharedGlobalObjects()

Actual Results:
Error's out at specific line preventing it from continuing forward.

**Comment by drkameleon** [comment]
The error is `unrecognised #identifier` right?

**Comment by jermowatson** [comment]
Its either the * or the = I'm not sure as I can't see your side of the code. But I suspect its one of the operators.

**Comment by drkameleon** [comment]
Well... let me tell you...

If the exact line of code is:
```objective-c
GlobalObjects *setObjects = [GlobalObjects sharedGlobalObjects];
```

Then the culprit is a known one (mentioned in at least 4-5 other issues here - probably I'm going to merge them) and it has to do with `GlobalObjects` not being recognized as a valid type.

I'm looking into it - those "unrecognized types" is at the top of my list.

**Comment by drkameleon** [comment]
Closed as related to: https://github.com/drkameleon/iswift/issues/42
